version: "3.3"

services:
  pyload:
    image: ghcr.io/linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/docker/pyload/config:/config
      - /mnt/docker/pyload/downloads:/downloads
    ports:
      - 8100:8000
      - 7227:7227 #optional
    restart: unless-stopped
