version: "3.3"

services:
  ytdl_material:
    environment:
      ALLOW_CONFIG_MUTATIONS: 'true'
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
      UID: 1024
      GID: ${PGID}
    restart: unless-stopped
    volumes:
      - /mnt/docker/ytdl_material/appdata:/app/appdata
      - /mnt/docker/ytdl_material/audio:/app/audio
      - /mnt/docker/ytdl_material/video:/app/video
      - /mnt/docker/ytdl_material/subscriptions:/app/subscriptions
      - /mnt/docker/ytdl_material/users:/app/users
    ports:
      - "8998:17442"
    image: tzahi12345/youtubedl-material:nightly

  ytdl-mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: "json-file"
    container_name: mongo-db
    volumes:
      - ./db:/data/db
