version: "3.3"

services:
  n8n:
    hostname: n8n
    image: n8nio/n8n
    container_name: n8n
    volumes:
      - /mnt/docker/n8n:/home/node/.n8n
    ports:
      - 5678:5678
    environment:
      - TZ=Europe/Brussels

