version: "3.3"

services:
  transmission:
    hostname: transmission
    image: haugene/transmission-openvpn
    container_name: transmission
    volumes:
      - /mnt/docker/transmission:/data
      - /mnt/downloads/transmission_incomplete:/downloads/incomplete
      - /mnt/downloads/completed_downloads:/downloads/completed
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9091:9091
    environment:
      - "CREATE_TUN_DEVICE=true"
      - "OPENVPN_PROVIDER=NORDVPN"
      - "NORDVPN_COUNTRY=${NORDVPN_COUNTRY}"
      - "OPENVPN_USERNAME=${NORDVPN_USER}"
      - "OPENVPN_PASSWORD=${NORDVPN_PASS}"
      - "WEBPROXY_ENABLED=false"
      - "TRANSMISSION_BLOCKLIST_ENABLED=true"
      - "TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz"
      - "TRANSMISSION_INCOMPLETE_DIR_ENABLED=true"
      - "TRANSMISSION_DOWNLOAD_DIR=/downloads/completed"
      - "TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete"
      - "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true"
      - "TRANSMISSION_RPC_USERNAME=transmission"
      - "TRANSMISSION_RPC_PASSWORD={c2aa917ebcfc9d9b3ce9fac95c83e72335ff1dccCfPdLwe7"
      - "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
      - "LOCAL_NETWORK=192.168.1.0/24"
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  sabnzbd:
    hostname: sabnzbd
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - /mnt/docker/sabnzbd:/config
      - /mnt/downloads/completed_downloads:/downloads
      - /mnt/downloads/sabnzbd_incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
      - SABNZBD_UID=1024
      - SABNZBD_GID=${PGID}

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /data/sonarr:/config
      - /mnt/media/TV:/tv
      - /mnt/downloads/completed_downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /data/radarr:/config
      - /mnt/media/Movies:/movies
      - /mnt/downloads/completed_downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /data/bazarr:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/TV:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1024
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/docker/jackett:/config
      - /mnt/downloads/completed_downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=1024 # User ID to run as
      - PGID=${PGID} # Group ID to run as
    volumes:
      - /mnt/docker/overseerr:/config
    ports:
      - 5055:5055/tcp # Web UI
