version: "3.3"

services:
  trilium:
    build:
      context: .
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "8081:8080"
    volumes:
      - /mnt/docker/trilium:/data

volumes:
  trilium:
