version: "3.3"

services:
  trilium:
    image: zadam/trilium
    container_name: trilium
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - /mnt/docker/trilium:/home/node/trilium-data
