version: "3.3"

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /mnt/docker/calibre/config:/config
      - /mnt/docker/calibre/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
