version: "3.3"

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=${CLOUDFLARE_ZONE}
      - PROXIED=true

  pwndrop:
    image: lscr.io/linuxserver/pwndrop
    container_name: pwndrop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/docker/pwndrop:/config
    ports:
      - 8082:8080
    restart: unless-stopped

  speedtest:
    hostname: speedtest
    image: henrywhitaker3/speedtest-tracker
    container_name: speedtest
    volumes:
      - /home/cviorel/speedtest-tracker:/config
    ports:
      - 8765:80
    environment:
      - OOKLA_EULA_GDPR=true
